<?php

namespace JLG\Sidebar\Settings;

use function __;

class DefaultSettings
{
    public const WIDGET_SCHEMAS = [
        'cta' => [
            'label' => 'Bloc CTA',
            'description' => 'Encourage une action clé avec un titre, un texte descriptif et un bouton de conversion.',
            'content' => [
                'title' => [
                    'type' => 'text',
                    'label' => 'Titre',
                    'default' => '',
                    'placeholder' => 'Boostez vos conversions',
                ],
                'message' => [
                    'type' => 'richtext',
                    'label' => 'Message',
                    'default' => '',
                    'placeholder' => 'Présentez votre offre en quelques phrases.',
                ],
                'button_label' => [
                    'type' => 'text',
                    'label' => 'Libellé du bouton',
                    'default' => '',
                    'placeholder' => 'Je découvre',
                ],
                'button_url' => [
                    'type' => 'url',
                    'label' => 'Lien du bouton',
                    'default' => '',
                ],
                'shortcode' => [
                    'type' => 'textarea',
                    'label' => 'Shortcode complémentaire',
                    'default' => '',
                    'placeholder' => '[contact-form-7 id="123"]',
                ],
            ],
            'style' => [
                'layout' => [
                    'type' => 'select',
                    'label' => 'Disposition',
                    'choices' => ['stacked', 'inline', 'badge'],
                    'default' => 'stacked',
                ],
                'background_color' => [
                    'type' => 'color',
                    'label' => 'Couleur de fond',
                    'default' => 'rgba(15, 23, 42, 0.95)',
                ],
                'accent_color' => [
                    'type' => 'color',
                    'label' => 'Couleur d\'accent',
                    'default' => 'rgba(37, 99, 235, 1)',
                ],
                'text_color' => [
                    'type' => 'color',
                    'label' => 'Couleur de texte',
                    'default' => 'rgba(241, 245, 249, 1)',
                ],
                'border_radius' => [
                    'type' => 'dimension',
                    'label' => 'Rayon des bords',
                    'default' => ['value' => '20', 'unit' => 'px'],
                    'units' => ['px', 'rem', 'em'],
                ],
                'shadow' => [
                    'type' => 'select',
                    'label' => 'Ombre',
                    'choices' => ['none', 'soft', 'emphasis'],
                    'default' => 'soft',
                ],
            ],
            'tracking' => [
                'events' => [
                    'view' => 'cta_view',
                    'interaction' => 'cta_click',
                    'conversion' => 'cta_conversion',
                ],
                'fields' => [
                    'goal_id' => [
                        'type' => 'text',
                        'label' => 'Identifiant de l\'objectif',
                        'default' => '',
                    ],
                    'conversion_label' => [
                        'type' => 'text',
                        'label' => 'Label de conversion',
                        'default' => '',
                    ],
                    'enable_goal' => [
                        'type' => 'boolean',
                        'label' => 'Activer le suivi de conversion',
                        'default' => true,
                    ],
                ],
            ],
        ],
        'form' => [
            'label' => 'Formulaire',
            'description' => 'Intègre un formulaire HTML ou un shortcode de collecte de leads.',
            'content' => [
                'title' => [
                    'type' => 'text',
                    'label' => 'Titre',
                    'default' => '',
                    'placeholder' => 'Restons en contact',
                ],
                'intro' => [
                    'type' => 'richtext',
                    'label' => 'Accroche',
                    'default' => '',
                    'placeholder' => 'Expliquez l\'intérêt du formulaire en une phrase.',
                ],
                'shortcode' => [
                    'type' => 'textarea',
                    'label' => 'Shortcode de formulaire',
                    'default' => '',
                ],
                'success_message' => [
                    'type' => 'textarea',
                    'label' => 'Message de succès',
                    'default' => '',
                    'placeholder' => 'Merci ! Nous revenons vers vous rapidement.',
                ],
            ],
            'style' => [
                'background_color' => [
                    'type' => 'color',
                    'label' => 'Couleur de fond',
                    'default' => 'rgba(15, 118, 110, 0.08)',
                ],
                'text_color' => [
                    'type' => 'color',
                    'label' => 'Texte',
                    'default' => 'rgba(15, 23, 42, 1)',
                ],
                'button_style' => [
                    'type' => 'select',
                    'label' => 'Style des boutons',
                    'choices' => ['solid', 'outline', 'ghost'],
                    'default' => 'solid',
                ],
                'padding' => [
                    'type' => 'dimension',
                    'label' => 'Marges internes',
                    'default' => ['value' => '24', 'unit' => 'px'],
                    'units' => ['px', 'rem', 'em'],
                ],
                'border_radius' => [
                    'type' => 'dimension',
                    'label' => 'Arrondi',
                    'default' => ['value' => '16', 'unit' => 'px'],
                    'units' => ['px', 'rem', 'em'],
                ],
            ],
            'tracking' => [
                'events' => [
                    'view' => 'form_view',
                    'interaction' => 'form_start',
                    'conversion' => 'form_submit',
                ],
                'fields' => [
                    'integration' => [
                        'type' => 'select',
                        'label' => 'Type d\'intégration',
                        'choices' => ['shortcode', 'html', 'hubspot', 'mailchimp'],
                        'default' => 'shortcode',
                    ],
                    'goal_id' => [
                        'type' => 'text',
                        'label' => 'Identifiant de conversion',
                        'default' => '',
                    ],
                    'enable_goal' => [
                        'type' => 'boolean',
                        'label' => 'Activer le suivi de soumission',
                        'default' => true,
                    ],
                ],
            ],
        ],
        'slider' => [
            'label' => 'Slider',
            'description' => 'Affiche un carrousel de témoignages, logos ou contenus personnalisés.',
            'content' => [
                'title' => [
                    'type' => 'text',
                    'label' => 'Titre du slider',
                    'default' => '',
                ],
                'items' => [
                    'type' => 'repeater',
                    'label' => 'Éléments du slider',
                    'default' => [
                        [
                            'heading' => 'Satisfaction client',
                            'text' => '95% des utilisateurs recommandent notre solution.',
                            'media' => '',
                            'media_alt' => '',
                            'caption' => '',
                        ],
                    ],
                    'schema' => [
                        'heading' => [
                            'type' => 'text',
                            'label' => 'Titre',
                            'default' => '',
                        ],
                        'text' => [
                            'type' => 'textarea',
                            'label' => 'Description',
                            'default' => '',
                        ],
                        'media' => [
                            'type' => 'url',
                            'label' => 'Image (URL)',
                            'default' => '',
                        ],
                        'media_alt' => [
                            'type' => 'text',
                            'label' => __('Texte alternatif', 'sidebar-jlg'),
                            'default' => '',
                        ],
                        'caption' => [
                            'type' => 'text',
                            'label' => __('Légende', 'sidebar-jlg'),
                            'default' => '',
                        ],
                    ],
                ],
                'controls_description' => [
                    'type' => 'textarea',
                    'label' => __('Consigne d’utilisation des contrôles', 'sidebar-jlg'),
                    'default' => '',
                ],
            ],
            'style' => [
                'theme' => [
                    'type' => 'select',
                    'label' => 'Thème visuel',
                    'choices' => ['minimal', 'cards', 'highlight'],
                    'default' => 'cards',
                ],
                'autoplay' => [
                    'type' => 'boolean',
                    'label' => 'Lecture automatique',
                    'default' => true,
                ],
                'autoplay_delay' => [
                    'type' => 'number',
                    'label' => 'Délai (ms)',
                    'default' => 4500,
                ],
            ],
            'tracking' => [
                'events' => [
                    'view' => 'slider_view',
                    'interaction' => 'slider_interaction',
                    'conversion' => 'slider_cta',
                ],
                'fields' => [
                    'enable_goal' => [
                        'type' => 'boolean',
                        'label' => 'Suivre les interactions',
                        'default' => true,
                    ],
                    'goal_id' => [
                        'type' => 'text',
                        'label' => 'Identifiant analytique',
                        'default' => '',
                    ],
                ],
            ],
        ],
        'woocommerce' => [
            'label' => 'WooCommerce',
            'description' => 'Met en avant des produits, catégories ou le panier WooCommerce.',
            'content' => [
                'mode' => [
                    'type' => 'select',
                    'label' => 'Mode d\'intégration',
                    'choices' => ['product', 'category', 'cart', 'checkout'],
                    'default' => 'product',
                ],
                'ids' => [
                    'type' => 'text',
                    'label' => 'Identifiants cibles',
                    'default' => '',
                    'placeholder' => '42,51,87',
                ],
                'fallback_message' => [
                    'type' => 'textarea',
                    'label' => 'Message alternatif',
                    'default' => '',
                ],
            ],
            'style' => [
                'display' => [
                    'type' => 'select',
                    'label' => 'Affichage',
                    'choices' => ['list', 'grid', 'compact'],
                    'default' => 'compact',
                ],
                'highlight_badges' => [
                    'type' => 'boolean',
                    'label' => 'Mettre en avant les promotions',
                    'default' => true,
                ],
                'background_color' => [
                    'type' => 'color',
                    'label' => 'Fond',
                    'default' => 'rgba(255, 255, 255, 1)',
                ],
            ],
            'tracking' => [
                'events' => [
                    'view' => 'woocommerce_widget_view',
                    'interaction' => 'woocommerce_widget_click',
                    'conversion' => 'woocommerce_widget_purchase',
                ],
                'fields' => [
                    'enable_goal' => [
                        'type' => 'boolean',
                        'label' => 'Suivre les clics produits',
                        'default' => true,
                    ],
                    'goal_id' => [
                        'type' => 'text',
                        'label' => 'Identifiant de l\'objectif',
                        'default' => '',
                    ],
                    'integration' => [
                        'type' => 'select',
                        'label' => 'Source des données',
                        'choices' => ['products', 'cart', 'checkout', 'recommendations'],
                        'default' => 'products',
                    ],
                ],
            ],
        ],
    ];
    public const STYLE_PRESETS = [
        'headless_minimal' => [
            'label' => 'Headless Minimal',
            'description' => 'Base neutre, contraste accessible et accent bleu inspirés de Headless UI.',
            'preview' => [
                'background' => '#f4f4f5',
                'accent' => '#2563eb',
                'text' => '#111827',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(244, 244, 245, 1)',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(37, 99, 235, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(17, 24, 39, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(29, 78, 216, 1)',
                'font_family' => 'system-ui',
                'font_weight' => '500',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0', 'unit' => 'em'],
                'hover_effect_desktop' => 'underline-center',
                'hover_effect_mobile' => 'underline-center',
                'animation_type' => 'fade',
                'mobile_bg_color' => 'rgba(255, 255, 255, 0.95)',
                'mobile_bg_opacity' => 0.95,
                'mobile_blur' => 6,
                'border_radius' => ['value' => '18', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(209, 213, 219, 0.7)',
            ],
        ],
        'shadcn_soft' => [
            'label' => 'Shadcn Neutrals',
            'description' => 'Palette sombre veloutée avec accents violets et typographie soignée à la Shadcn UI.',
            'preview' => [
                'background' => 'linear-gradient(180deg, #0f172a 0%, #020617 100%)',
                'accent' => '#8b5cf6',
                'text' => '#e2e8f0',
            ],
            'settings' => [
                'bg_color_type' => 'gradient',
                'bg_color' => 'rgba(15, 23, 42, 1)',
                'bg_color_start' => '#0f172a',
                'bg_color_end' => '#020617',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(139, 92, 246, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(226, 232, 240, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'google-roboto',
                'font_weight' => '500',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0.02', 'unit' => 'em'],
                'hover_effect_desktop' => 'underline-center',
                'hover_effect_mobile' => 'underline-center',
                'animation_type' => 'fade',
                'mobile_bg_color' => 'rgba(15, 23, 42, 0.92)',
                'mobile_bg_opacity' => 0.92,
                'mobile_blur' => 16,
                'border_radius' => ['value' => '20', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(76, 29, 149, 0.55)',
            ],
        ],
        'moderne_dark' => [
            'label' => 'Critique Moderne (Sombre)',
            'description' => 'Contraste marqué, typographie audacieuse et accent électrique.',
            'preview' => [
                'background' => 'linear-gradient(180deg, #1f2937 0%, #111827 100%)',
                'accent' => '#0d6efd',
                'text' => '#f8fafc',
            ],
            'settings' => [
                'bg_color_type' => 'gradient',
                'bg_color' => 'rgba(31, 41, 55, 1)',
                'bg_color_start' => '#1f2937',
                'bg_color_end' => '#111827',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(13, 110, 253, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(248, 250, 252, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'google-montserrat',
                'font_weight' => '600',
                'text_transform' => 'uppercase',
                'letter_spacing' => ['value' => '0.08', 'unit' => 'em'],
                'hover_effect_desktop' => 'underline-center',
                'hover_effect_mobile' => 'underline-center',
                'animation_type' => 'slide-left',
                'mobile_bg_color' => 'rgba(15, 23, 42, 0.85)',
                'mobile_bg_opacity' => 0.85,
                'mobile_blur' => 12,
                'border_radius' => ['value' => '18', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(148, 163, 184, 0.35)',
            ],
        ],
        'radix_neutrals' => [
            'label' => 'Radix Neutrals',
            'description' => 'Équilibre sombre élégant, surfaces superposées et accents violets inspirés de Radix UI.',
            'preview' => [
                'background' => 'linear-gradient(180deg, #1a1a1f 0%, #111114 100%)',
                'accent' => '#6e56cf',
                'text' => '#ededef',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(24, 24, 27, 1)',
                'accent_color_type' => 'gradient',
                'accent_color' => 'rgba(110, 86, 207, 1)',
                'accent_color_start' => '#6e56cf',
                'accent_color_end' => '#9d5cf6',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(237, 237, 239, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'system-ui',
                'font_weight' => '500',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0.02', 'unit' => 'em'],
                'hover_effect_desktop' => 'underline-center',
                'hover_effect_mobile' => 'underline-center',
                'animation_type' => 'fade',
                'mobile_bg_color' => 'rgba(24, 24, 27, 0.92)',
                'mobile_bg_opacity' => 0.92,
                'mobile_blur' => 16,
                'border_radius' => ['value' => '18', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(62, 62, 68, 0.65)',
            ],
        ],
        'bootstrap_classic' => [
            'label' => 'Bootstrap Classique',
            'description' => 'Blocs clairs, bordures subtiles et bleu signature Bootstrap.',
            'preview' => [
                'background' => '#f8f9fa',
                'accent' => '#0d6efd',
                'text' => '#212529',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(248, 249, 250, 1)',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(13, 110, 253, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(33, 37, 41, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(25, 118, 210, 1)',
                'font_family' => 'google-open-sans',
                'font_weight' => '600',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0', 'unit' => 'em'],
                'hover_effect_desktop' => 'none',
                'hover_effect_mobile' => 'none',
                'animation_type' => 'slide-left',
                'mobile_bg_color' => 'rgba(255, 255, 255, 0.95)',
                'mobile_bg_opacity' => 0.95,
                'mobile_blur' => 4,
                'border_radius' => ['value' => '12', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(222, 226, 230, 1)',
            ],
        ],
        'semantic_fresh' => [
            'label' => 'Semantic Fresh',
            'description' => 'Ambiance sombre chic et accent turquoise rappelant Semantic UI.',
            'preview' => [
                'background' => '#1b1c1d',
                'accent' => '#00b5ad',
                'text' => '#f9fafb',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(27, 28, 29, 1)',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(0, 181, 173, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(249, 250, 251, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'google-roboto',
                'font_weight' => '500',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0.03', 'unit' => 'em'],
                'hover_effect_desktop' => 'tile-slide',
                'hover_effect_mobile' => 'tile-slide',
                'animation_type' => 'slide-left',
                'mobile_bg_color' => 'rgba(27, 28, 29, 0.94)',
                'mobile_bg_opacity' => 0.94,
                'mobile_blur' => 14,
                'border_radius' => ['value' => '18', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(0, 181, 173, 0.35)',
            ],
        ],
        'minimal_light' => [
            'label' => 'Minimal Clair',
            'description' => 'Palette douce, lisibilité maximale et transitions discrètes.',
            'preview' => [
                'background' => '#f8fafc',
                'accent' => '#2563eb',
                'text' => '#1f2937',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(248, 250, 252, 1)',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(37, 99, 235, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(30, 41, 59, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(15, 118, 110, 1)',
                'font_family' => 'google-open-sans',
                'font_weight' => '400',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0', 'unit' => 'em'],
                'hover_effect_desktop' => 'none',
                'hover_effect_mobile' => 'none',
                'animation_type' => 'fade',
                'mobile_bg_color' => 'rgba(255, 255, 255, 0.95)',
                'mobile_bg_opacity' => 0.95,
                'mobile_blur' => 4,
                'border_radius' => ['value' => '14', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(148, 163, 184, 0.2)',
            ],
        ],
        'retro_warm' => [
            'label' => 'Retro & Chaleur',
            'description' => 'Dégradé chaleureux, touches vintage et boutons arrondis.',
            'preview' => [
                'background' => 'linear-gradient(180deg, #f97316 0%, #db2777 100%)',
                'accent' => '#fb923c',
                'text' => '#fff7ed',
            ],
            'settings' => [
                'bg_color_type' => 'gradient',
                'bg_color' => 'rgba(249, 115, 22, 1)',
                'bg_color_start' => '#f97316',
                'bg_color_end' => '#db2777',
                'accent_color_type' => 'gradient',
                'accent_color' => 'rgba(251, 191, 36, 1)',
                'accent_color_start' => '#fde68a',
                'accent_color_end' => '#f97316',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(255, 247, 237, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'georgia',
                'font_weight' => '600',
                'text_transform' => 'capitalize',
                'letter_spacing' => ['value' => '0.05', 'unit' => 'em'],
                'hover_effect_desktop' => 'pill-center',
                'hover_effect_mobile' => 'pill-center',
                'animation_type' => 'scale',
                'mobile_bg_color' => 'rgba(251, 191, 36, 0.92)',
                'mobile_bg_opacity' => 0.92,
                'mobile_blur' => 6,
                'border_radius' => ['value' => '24', 'unit' => 'px'],
                'border_width' => 2,
                'border_color' => 'rgba(251, 146, 60, 0.35)',
            ],
        ],
        'glass_neon' => [
            'label' => 'Verre Néon',
            'description' => 'Effet glassmorphism, néons vibrants et ambiance futuriste.',
            'preview' => [
                'background' => 'linear-gradient(180deg, rgba(15, 23, 42, 0.85) 0%, rgba(30, 41, 59, 0.65) 100%)',
                'accent' => 'linear-gradient(135deg, #38bdf8 0%, #f472b6 100%)',
                'text' => '#e2e8f0',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(15, 23, 42, 0.75)',
                'accent_color_type' => 'gradient',
                'accent_color' => 'rgba(56, 189, 248, 1)',
                'accent_color_start' => '#38bdf8',
                'accent_color_end' => '#f472b6',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(226, 232, 240, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'google-roboto',
                'font_weight' => '500',
                'text_transform' => 'uppercase',
                'letter_spacing' => ['value' => '0.12', 'unit' => 'em'],
                'hover_effect_desktop' => 'glow',
                'hover_effect_mobile' => 'glow',
                'animation_type' => 'fade',
                'mobile_bg_color' => 'rgba(15, 23, 42, 0.9)',
                'mobile_bg_opacity' => 0.9,
                'mobile_blur' => 18,
                'border_radius' => ['value' => '32', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(148, 163, 184, 0.6)',
            ],
        ],
        'anime_neon' => [
            'label' => 'Anime.js Néon',
            'description' => 'Dégradé vibrant, effets lumineux et accents dynamiques inspirés d’Anime.js.',
            'preview' => [
                'background' => 'linear-gradient(180deg, #0f172a 0%, #312e81 100%)',
                'accent' => 'linear-gradient(135deg, #38bdf8 0%, #f472b6 100%)',
                'text' => '#e0e7ff',
            ],
            'settings' => [
                'bg_color_type' => 'gradient',
                'bg_color' => 'rgba(17, 24, 39, 1)',
                'bg_color_start' => '#0f172a',
                'bg_color_end' => '#312e81',
                'accent_color_type' => 'gradient',
                'accent_color' => 'rgba(56, 189, 248, 1)',
                'accent_color_start' => '#38bdf8',
                'accent_color_end' => '#f472b6',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(224, 231, 255, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(244, 114, 182, 1)',
                'font_family' => 'google-montserrat',
                'font_weight' => '600',
                'text_transform' => 'uppercase',
                'letter_spacing' => ['value' => '0.1', 'unit' => 'em'],
                'hover_effect_desktop' => 'glow',
                'hover_effect_mobile' => 'glow',
                'animation_type' => 'scale',
                'mobile_bg_color' => 'rgba(17, 24, 39, 0.9)',
                'mobile_bg_opacity' => 0.9,
                'mobile_blur' => 18,
                'border_radius' => ['value' => '28', 'unit' => 'px'],
                'border_width' => 2,
                'border_color' => 'rgba(56, 189, 248, 0.45)',
                'neon_blur' => 22,
                'neon_spread' => 7,
            ],
        ],
        'astra_modern' => [
            'label' => 'Astra Modern',
            'description' => 'Palette marine et turquoise alignée sur les interfaces Astra et leurs contraintes WCAG.',
            'preview' => [
                'background' => 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)',
                'accent' => '#0ea5e9',
                'text' => '#f8fafc',
            ],
            'settings' => [
                'bg_color_type' => 'gradient',
                'bg_color' => 'rgba(15, 23, 42, 1)',
                'bg_color_start' => '#0f172a',
                'bg_color_end' => '#1e293b',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(14, 165, 233, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(248, 250, 252, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(125, 211, 252, 1)',
                'font_family' => 'google-open-sans',
                'font_weight' => '600',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0.02', 'unit' => 'em'],
                'hover_effect_desktop' => 'underline-center',
                'hover_effect_mobile' => 'underline-center',
                'animation_type' => 'slide-left',
                'mobile_bg_color' => 'rgba(15, 23, 42, 0.92)',
                'mobile_bg_opacity' => 0.92,
                'mobile_blur' => 14,
                'border_radius' => ['value' => '20', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(14, 165, 233, 0.35)',
            ],
        ],
        'divi_sleek' => [
            'label' => 'Divi Sleek',
            'description' => 'Dégradé violet-orangé, boutons pill et animations punchy inspirés de Divi.',
            'preview' => [
                'background' => 'linear-gradient(135deg, #2a1747 0%, #431e61 100%)',
                'accent' => 'linear-gradient(135deg, #f472b6 0%, #f97316 100%)',
                'text' => '#fdf4ff',
            ],
            'settings' => [
                'bg_color_type' => 'gradient',
                'bg_color' => 'rgba(42, 23, 71, 1)',
                'bg_color_start' => '#2a1747',
                'bg_color_end' => '#431e61',
                'accent_color_type' => 'gradient',
                'accent_color' => 'rgba(244, 114, 182, 1)',
                'accent_color_start' => '#f472b6',
                'accent_color_end' => '#f97316',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(253, 244, 255, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(255, 255, 255, 1)',
                'font_family' => 'google-montserrat',
                'font_weight' => '600',
                'text_transform' => 'uppercase',
                'letter_spacing' => ['value' => '0.06', 'unit' => 'em'],
                'hover_effect_desktop' => 'pill-center',
                'hover_effect_mobile' => 'pill-center',
                'animation_type' => 'scale',
                'mobile_bg_color' => 'rgba(33, 17, 58, 0.9)',
                'mobile_bg_opacity' => 0.9,
                'mobile_blur' => 18,
                'border_radius' => ['value' => '26', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(244, 114, 182, 0.55)',
                'neon_blur' => 20,
                'neon_spread' => 6,
            ],
        ],
        'bricks_neutral' => [
            'label' => 'Bricks Neutral',
            'description' => 'Tons sable et gris chauds avec accent cuivre, calibrés pour les layouts Bricks Builder.',
            'preview' => [
                'background' => '#f5f1eb',
                'accent' => '#f97316',
                'text' => '#1f2937',
            ],
            'settings' => [
                'bg_color_type' => 'solid',
                'bg_color' => 'rgba(245, 241, 235, 1)',
                'accent_color_type' => 'solid',
                'accent_color' => 'rgba(249, 115, 22, 1)',
                'font_color_type' => 'solid',
                'font_color' => 'rgba(31, 41, 55, 1)',
                'font_hover_color_type' => 'solid',
                'font_hover_color' => 'rgba(180, 83, 9, 1)',
                'font_family' => 'system-ui',
                'font_weight' => '500',
                'text_transform' => 'none',
                'letter_spacing' => ['value' => '0.01', 'unit' => 'em'],
                'hover_effect_desktop' => 'spotlight',
                'hover_effect_mobile' => 'spotlight',
                'animation_type' => 'slide-left',
                'mobile_bg_color' => 'rgba(253, 252, 250, 0.95)',
                'mobile_bg_opacity' => 0.95,
                'mobile_blur' => 6,
                'border_radius' => ['value' => '16', 'unit' => 'px'],
                'border_width' => 1,
                'border_color' => 'rgba(214, 211, 209, 1)',
            ],
        ],
    ];

    /**
     * Returns the default plugin settings.
     */
    public function all(): array
    {
        return [
            'enable_sidebar'    => true,
            'enable_analytics'  => false,
            'app_name'          => 'Sidebar JLG',
            'layout_style'      => 'full',
            'sidebar_position'  => 'left',
            'floating_vertical_margin'   => ['value' => '4', 'unit' => 'rem'],
            'horizontal_bar_height'      => ['value' => '4', 'unit' => 'rem'],
            'horizontal_bar_alignment'   => 'space-between',
            'horizontal_bar_position'    => 'top',
            'horizontal_bar_sticky'      => true,
            'border_radius'     => ['value' => '12', 'unit' => 'px'],
            'border_width'      => 1,
            'border_color'      => 'rgba(255,255,255,0.2)',
            'desktop_behavior'  => 'push',
            'overlay_color'     => 'rgba(0, 0, 0, 1)',
            'overlay_opacity'   => 0.5,
            'content_margin'    => ['value' => '2', 'unit' => 'rem'],
            'width_desktop'     => 280,
            'width_tablet'      => 320,
            'width_mobile'      => '100%',
            'enable_search'     => false,
            'search_method'     => 'default',
            'search_shortcode'  => '',
            'search_alignment'  => 'flex-start',
            'debug_mode'        => false,
            'show_close_button' => true,
            // Automatically close the sidebar after clicking menu or social links.
            'close_on_link_click' => false,
            // Persist open state, scroll position and interactions between page loads.
            'remember_last_state' => false,
            // Touch gestures to align with premium off-canvas experiences.
            'touch_gestures_edge_swipe' => false,
            'touch_gestures_close_swipe' => true,
            'touch_gestures_edge_size' => 32,
            'touch_gestures_min_distance' => 95,
            // Auto-open helpers triggered by visitor behaviour. Values set to 0 disable the trigger.
            'auto_open_time_delay' => 0,
            'auto_open_scroll_depth' => 0,
            'auto_open_exit_intent' => false,
            'auto_open_inactivity_delay' => 0,
            'nav_aria_label'   => '',
            'toggle_open_label'  => '',
            'toggle_close_label' => '',
            'hamburger_top_position'     => ['value' => '4', 'unit' => 'rem'],
            'hamburger_horizontal_offset' => ['value' => '15', 'unit' => 'px'],
            'hamburger_size'             => ['value' => '50', 'unit' => 'px'],
            'hamburger_color'            => 'rgba(255, 255, 255, 1)',
            'header_logo_type'  => 'text',
            'header_logo_image' => '',
            'header_logo_size'  => 150,
            'header_alignment_desktop'  => 'flex-start',
            'header_alignment_mobile'   => 'center',
            'header_padding_top' => ['value' => '2.5', 'unit' => 'rem'],
            'style_preset'      => 'custom',
            'bg_color_type'     => 'solid',
            'bg_color'          => 'rgba(26, 29, 36, 1)',
            'bg_color_start'    => '#18181b',
            'bg_color_end'      => '#27272a',
            'accent_color_type' => 'solid',
            'accent_color'      => 'rgba(13, 110, 253, 1)',
            'accent_color_start'=> '#60a5fa',
            'accent_color_end'  => '#c084fc',
            'font_size'         => 16,
            'font_family'       => 'system-ui',
            'font_weight'       => '400',
            'text_transform'    => 'none',
            'letter_spacing'    => ['value' => '0', 'unit' => 'em'],
            'font_color_type'   => 'solid',
            'font_color'        => 'rgba(224, 224, 224, 1)',
            'font_color_start'  => '#fafafa',
            'font_color_end'    => '#e0e0e0',
            'font_hover_color_type' => 'solid',
            'font_hover_color'  => 'rgba(255, 255, 255, 1)',
            'font_hover_color_start' => '#ffffff',
            'font_hover_color_end'   => '#fafafa',
            'mobile_bg_color'   => 'rgba(26, 29, 36, 0.8)',
            'mobile_bg_opacity' => 0.8,
            'mobile_blur'       => 10,
            'hover_effect_desktop'   => 'none',
            'hover_effect_mobile'    => 'none',
            'animation_speed'   => 400,
            'animation_type'    => 'slide-left',
            'neon_blur'         => 15,
            'neon_spread'       => 5,
            'menu_items'        => [
                [
                    'label'     => \__( 'Accueil', 'sidebar-jlg' ),
                    'type'      => 'custom',
                    'icon_type' => 'svg_inline',
                    'icon'      => '',
                    'value'     => '#accueil',
                ],
                [
                    'label'     => \__( 'Tests', 'sidebar-jlg' ),
                    'type'      => 'custom',
                    'icon_type' => 'svg_inline',
                    'icon'      => '',
                    'value'     => '#tests',
                ],
                [
                    'label'     => \__( 'Articles', 'sidebar-jlg' ),
                    'type'      => 'custom',
                    'icon_type' => 'svg_inline',
                    'icon'      => '',
                    'value'     => '#articles',
                ],
                [
                    'label'     => \__( 'Pages', 'sidebar-jlg' ),
                    'type'      => 'custom',
                    'icon_type' => 'svg_inline',
                    'icon'      => '',
                    'value'     => '#pages',
                ],
            ],
            'menu_alignment_desktop' => 'flex-start',
            'menu_alignment_mobile'  => 'flex-start',
            'social_icons'      => [
                ['url' => '#', 'icon' => 'youtube_white', 'label' => ''],
                ['url' => '#', 'icon' => 'x_white', 'label' => ''],
                ['url' => '#', 'icon' => 'facebook_white', 'label' => ''],
                ['url' => '#', 'icon' => 'instagram_white', 'label' => ''],
            ],
            'social_orientation'=> 'horizontal',
            'social_position'   => 'footer',
            'social_icon_size'  => 100,
            'style_presets'     => self::STYLE_PRESETS,
            'widgets'           => [],
            'widget_schemas'    => self::WIDGET_SCHEMAS,
        ];
    }

    public function getStylePresets(): array
    {
        return self::STYLE_PRESETS;
    }
}
